package com.chessyoup.chess.model;

import com.chessyoup.chess.model.exception.IllegalMoveException;

/**
 * Created by leo on 17.10.2014.
 */
public interface Chessboard {

    public enum MODE { PLAY , ANALYSIS }

    public interface ChessboardListener {

        public void onChange(Chessboard source);

        public void onResult(Chessboard source);
    }

    public MODE getMode();

    public void setMode(MODE mode);

    /**
     * Get the chess tree for this chessboard.
     * @return
     */
    public Tree getMovesTree();

    /**
     *
     * @return
     */
    public Square getSquare(char file , int rank);

    /**
     * Get current position on the chessboard
     * @return
     */
    public Position getPosition();

    /**
     * Apply this move on current position.
     * This will generate an event.
     * @param move - the move to apply
     * @throws IllegalMoveException - if this is an illegal move.
     */
    public void doMove(Move move) throws IllegalMoveException;

    /**
     * Apply this move on current position.
     * No event will be generated by this.
     * @param move
     * @param silent
     * @throws IllegalMoveException
     */
    public void doMove(Move move,boolean silent) throws IllegalMoveException;

    /**
     * Undo last move.
     * This will generate an event.
     */
    public void undoMove();

    /**
     * Reset this chessboard to initial chess position using
     * FEN : rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1
     */
    public void reset();

    /**
     * Navigate to this Node in ANALYSIS mode.
     * This will trigger an event.
     * @param node - tree node to navigate , null for the start position ( root node )
     */
    public void goToNode(Node node);

    /**
     * Navigate 1 node forward from current node in ANALYSIS mode.
     * This will trigger an event.
     */
    public void goForward();

    /**
     * Navigate 1 node backward from current node in ANALYSIS mode.
     * This will trigger an event.
     */
    public void goBack();
}
